### PR TITLE
Srab 44 - k florek changes

### PR DESCRIPTION
**Pull request by multikengineer**
This includes all of k-florek's changes in a backwards compatible manner, and a tweak here and there.

### CODE REVIEW

**Comment by rpetit3** [comment]
Looks good to me!

Not trying to be difficult here. but I think it's worth mentioning that by creating a new PR, @k-florek's contributions will not show up in the commits (https://github.com/ncbi/sra-human-scrubber/commits/master) or the contributors list (https://github.com/ncbi/sra-human-scrubber/graphs/contributors)

I think @k-florek's body of work is impressive and speaks for itself. But as an early career scientist, I've found GitHub commits to be an extremely valuable metric for documenting scientific contributions. You never know, you might one day get a [PR](https://github.com/bactopia/bactopia/pull/228) that is the product of someone's entire internship!

**Comment by multikengineer** [comment]
@rpetit3  Not being difficult at all, and I fully agree. Since I could not take the changes as they were, and I was starting from the fork, I took the easier path.  Had I been able to use the changes out of the box then I would have.

**Comment by rpetit3** [comment]
Thank you very much Ken! It really means a lot. Cheers

**Comment by rpetit3** [comment]
One alternative to consider is editing the files in https://github.com/ncbi/sra-human-scrubber/pull/15 to include the changes you added.

**Comment by multikengineer** [comment]
Before coffee rescued commits for PR #16 for this, closing to merge with history intact.

**Pull request closed without merging**
